/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2020-04-20-cacdac8"
#endif /* AVUTIL_FFVERSION_H */
